Repository GSG-G11/amazona-team5, pull requests merged in 2022-02, with the labels that each got.

#2 create file structure
  .gitignore
  index.html
  logic.test.js
  package-lock.json
  package.json
  pages/cart.html
  pages/seller.html
  scripts/index.js
  scripts/logic.js
  styles/style.css
Labels: Awaiting Review

#17 create and style cards container
  index.html
  styles/style.css
Labels: Done

#18 5 footer
  index.html
  styles/style.css
Labels: Awaiting Review

#19 8 product form
  pages/seller.html
  styles/style.css
Labels: Awaiting Review

#21 3 header
  index.html
  pages/cart.html
  pages/seller.html
  styles/style.css
Labels: Awaiting Review

#32 add testing for addItem,deleteItem,getTotalPrice
  logic.test.js
  pages/cart.html
  scripts/logic.js
Labels: In Progress

#36 Write Read Me File
  README.md
Labels: Awaiting Review

#39 25 add item to cart
  logic.test.js
  pages/cart.html
  scripts/buyer.js
  scripts/index.js
  scripts/logic.js
Labels: Awaiting Review

#51 Delete from cart
  logic.test.js
  scripts/edit-seller.js
  scripts/index.js
  scripts/logic.js
Labels: Awaiting Review
